/* Automatically @generated by tree-sitter */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 41
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 29
#define ALIAS_COUNT 0
#define TOKEN_COUNT 17
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 7
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 1
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  anon_sym_LBRACK = 1,
  aux_sym_section_header_token1 = 2,
  anon_sym_RBRACK = 3,
  sym_section_name = 4,
  sym_condition = 5,
  sym_option_name = 6,
  sym_assignment = 7,
  aux_sym_value_token1 = 8,
  aux_sym_value_token2 = 9,
  sym_substitution = 10,
  sym_escape = 11,
  aux_sym_dependency_annotation_token1 = 12,
  aux_sym_continuation_token1 = 13,
  sym_comment = 14,
  sym__blank_line = 15,
  sym__newline = 16,
  sym_source_file = 17,
  sym_section = 18,
  sym_section_header = 19,
  sym_option = 20,
  sym_value = 21,
  sym_dependency_annotation = 22,
  sym_continuation = 23,
  sym__trailing_comment = 24,
  aux_sym_source_file_repeat1 = 25,
  aux_sym_section_repeat1 = 26,
  aux_sym_option_repeat1 = 27,
  aux_sym_value_repeat1 = 28,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_LBRACK] = "[",
  [aux_sym_section_header_token1] = "section_header_token1",
  [anon_sym_RBRACK] = "]",
  [sym_section_name] = "section_name",
  [sym_condition] = "condition",
  [sym_option_name] = "option_name",
  [sym_assignment] = "assignment",
  [aux_sym_value_token1] = "value_token1",
  [aux_sym_value_token2] = "value_token2",
  [sym_substitution] = "substitution",
  [sym_escape] = "escape",
  [aux_sym_dependency_annotation_token1] = "dependency_annotation_token1",
  [aux_sym_continuation_token1] = "continuation_token1",
  [sym_comment] = "comment",
  [sym__blank_line] = "_blank_line",
  [sym__newline] = "_newline",
  [sym_source_file] = "source_file",
  [sym_section] = "section",
  [sym_section_header] = "section_header",
  [sym_option] = "option",
  [sym_value] = "value",
  [sym_dependency_annotation] = "dependency_annotation",
  [sym_continuation] = "continuation",
  [sym__trailing_comment] = "_trailing_comment",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_section_repeat1] = "section_repeat1",
  [aux_sym_option_repeat1] = "option_repeat1",
  [aux_sym_value_repeat1] = "value_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [aux_sym_section_header_token1] = aux_sym_section_header_token1,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [sym_section_name] = sym_section_name,
  [sym_condition] = sym_condition,
  [sym_option_name] = sym_option_name,
  [sym_assignment] = sym_assignment,
  [aux_sym_value_token1] = aux_sym_value_token1,
  [aux_sym_value_token2] = aux_sym_value_token2,
  [sym_substitution] = sym_substitution,
  [sym_escape] = sym_escape,
  [aux_sym_dependency_annotation_token1] = aux_sym_dependency_annotation_token1,
  [aux_sym_continuation_token1] = aux_sym_continuation_token1,
  [sym_comment] = sym_comment,
  [sym__blank_line] = sym__blank_line,
  [sym__newline] = sym__newline,
  [sym_source_file] = sym_source_file,
  [sym_section] = sym_section,
  [sym_section_header] = sym_section_header,
  [sym_option] = sym_option,
  [sym_value] = sym_value,
  [sym_dependency_annotation] = sym_dependency_annotation,
  [sym_continuation] = sym_continuation,
  [sym__trailing_comment] = sym__trailing_comment,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_section_repeat1] = aux_sym_section_repeat1,
  [aux_sym_option_repeat1] = aux_sym_option_repeat1,
  [aux_sym_value_repeat1] = aux_sym_value_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_section_header_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [sym_section_name] = {
    .visible = true,
    .named = true,
  },
  [sym_condition] = {
    .visible = true,
    .named = true,
  },
  [sym_option_name] = {
    .visible = true,
    .named = true,
  },
  [sym_assignment] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_value_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_value_token2] = {
    .visible = false,
    .named = false,
  },
  [sym_substitution] = {
    .visible = true,
    .named = true,
  },
  [sym_escape] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_dependency_annotation_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_continuation_token1] = {
    .visible = false,
    .named = false,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym__blank_line] = {
    .visible = false,
    .named = true,
  },
  [sym__newline] = {
    .visible = false,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_section] = {
    .visible = true,
    .named = true,
  },
  [sym_section_header] = {
    .visible = true,
    .named = true,
  },
  [sym_option] = {
    .visible = true,
    .named = true,
  },
  [sym_value] = {
    .visible = true,
    .named = true,
  },
  [sym_dependency_annotation] = {
    .visible = true,
    .named = true,
  },
  [sym_continuation] = {
    .visible = true,
    .named = true,
  },
  [sym__trailing_comment] = {
    .visible = false,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_section_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_option_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_value_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
};

static const TSCharacterRange sym_section_name_character_set_1[] = {
  {0, 0x08}, {0x0e, 0x1f}, {'!', '"'}, {'$', '9'}, {'<', 'Z'}, {'\\', '\\'}, {'^', 'z'}, {'|', '|'},
  {'~', 0x10ffff},
};

static const TSCharacterRange sym_option_name_character_set_1[] = {
  {0, 0x08}, {0x0e, 0x1f}, {'!', '9'}, {';', '<'}, {'>', 'Z'}, {'\\', '\\'}, {'^', 'z'}, {'|', '|'},
  {'~', 0x10ffff},
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(14);
      ADVANCE_MAP(
        '\n', 32,
        '\r', 1,
        '$', 25,
        ':', 9,
        '=', 8,
        '[', 15,
        ']', 17,
        '\t', 16,
        ' ', 16,
        '#', 30,
        ';', 30,
      );
      END_STATE();
    case 1:
      if (lookahead == '\n') ADVANCE(32);
      END_STATE();
    case 2:
      if (lookahead == '\n') ADVANCE(32);
      if (lookahead == '\r') ADVANCE(23);
      if (lookahead == '$') ADVANCE(25);
      if (lookahead != 0) ADVANCE(24);
      END_STATE();
    case 3:
      if (lookahead == '\n') ADVANCE(31);
      END_STATE();
    case 4:
      if (lookahead == '\n') ADVANCE(31);
      if (lookahead == '\r') ADVANCE(3);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(4);
      END_STATE();
    case 5:
      if (lookahead == '\n') ADVANCE(31);
      if (lookahead == '\r') ADVANCE(3);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(5);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead)) ADVANCE(29);
      END_STATE();
    case 6:
      if (lookahead == '=') ADVANCE(22);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(6);
      if (lookahead == '+' ||
          lookahead == '-') ADVANCE(7);
      END_STATE();
    case 7:
      if (lookahead == '=') ADVANCE(22);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(7);
      END_STATE();
    case 8:
      if (lookahead == '>') ADVANCE(28);
      END_STATE();
    case 9:
      if (lookahead == ']') ADVANCE(19);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '#' &&
          lookahead != ';') ADVANCE(9);
      END_STATE();
    case 10:
      if (lookahead == '}') ADVANCE(26);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(10);
      END_STATE();
    case 11:
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(16);
      if ((!eof && set_contains(sym_section_name_character_set_1, 9, lookahead))) ADVANCE(18);
      END_STATE();
    case 12:
      if (eof) ADVANCE(14);
      ADVANCE_MAP(
        '\n', 31,
        '\r', 3,
        '=', 8,
        '[', 15,
        '\t', 5,
        ' ', 5,
        '#', 20,
        ';', 20,
      );
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ':' &&
          lookahead != ';' &&
          lookahead != ']' &&
          lookahead != '{' &&
          lookahead != '}') ADVANCE(21);
      END_STATE();
    case 13:
      if (eof) ADVANCE(14);
      if (lookahead == '\n') ADVANCE(31);
      if (lookahead == '\r') ADVANCE(3);
      if (lookahead == '[') ADVANCE(15);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(4);
      if (lookahead == '#' ||
          lookahead == ';') ADVANCE(30);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ':' &&
          lookahead != ';' &&
          lookahead != ']' &&
          lookahead != '{' &&
          lookahead != '}') ADVANCE(18);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(aux_sym_section_header_token1);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(16);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(sym_section_name);
      if ((!eof && set_contains(sym_section_name_character_set_1, 9, lookahead))) ADVANCE(18);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(sym_condition);
      if (lookahead == ']') ADVANCE(19);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '#' &&
          lookahead != ';') ADVANCE(9);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(sym_option_name);
      if (lookahead == '\t' ||
          (0x0b <= lookahead && lookahead <= '\r') ||
          lookahead == ' ' ||
          lookahead == ':' ||
          lookahead == '=' ||
          lookahead == '[' ||
          lookahead == ']' ||
          lookahead == '{' ||
          lookahead == '}') ADVANCE(30);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead)) ADVANCE(20);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(sym_option_name);
      if ((!eof && set_contains(sym_option_name_character_set_1, 9, lookahead))) ADVANCE(21);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(sym_assignment);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(22);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(aux_sym_value_token1);
      if (lookahead == '\n') ADVANCE(32);
      if (lookahead != 0 &&
          lookahead != '$') ADVANCE(24);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(aux_sym_value_token1);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '$') ADVANCE(24);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(aux_sym_value_token2);
      if (lookahead == '$') ADVANCE(27);
      if (lookahead == '{') ADVANCE(10);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(sym_substitution);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(sym_escape);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(aux_sym_dependency_annotation_token1);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(28);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(aux_sym_continuation_token1);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(29);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(30);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(sym__blank_line);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(sym__newline);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 13},
  [2] = {.lex_state = 12},
  [3] = {.lex_state = 12},
  [4] = {.lex_state = 12},
  [5] = {.lex_state = 12},
  [6] = {.lex_state = 12},
  [7] = {.lex_state = 12},
  [8] = {.lex_state = 12},
  [9] = {.lex_state = 12},
  [10] = {.lex_state = 12},
  [11] = {.lex_state = 12},
  [12] = {.lex_state = 12},
  [13] = {.lex_state = 13},
  [14] = {.lex_state = 2},
  [15] = {.lex_state = 13},
  [16] = {.lex_state = 12},
  [17] = {.lex_state = 2},
  [18] = {.lex_state = 2},
  [19] = {.lex_state = 12},
  [20] = {.lex_state = 12},
  [21] = {.lex_state = 12},
  [22] = {.lex_state = 0},
  [23] = {.lex_state = 0},
  [24] = {.lex_state = 0},
  [25] = {.lex_state = 0},
  [26] = {.lex_state = 0},
  [27] = {.lex_state = 11},
  [28] = {.lex_state = 0},
  [29] = {.lex_state = 0},
  [30] = {.lex_state = 0},
  [31] = {.lex_state = 13},
  [32] = {.lex_state = 0},
  [33] = {.lex_state = 0},
  [34] = {.lex_state = 0},
  [35] = {.lex_state = 6},
  [36] = {.lex_state = 0},
  [37] = {.lex_state = 0},
  [38] = {.lex_state = 0},
  [39] = {.lex_state = 0},
  [40] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [aux_sym_section_header_token1] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [sym_condition] = ACTIONS(1),
    [aux_sym_value_token2] = ACTIONS(1),
    [sym_substitution] = ACTIONS(1),
    [sym_escape] = ACTIONS(1),
    [aux_sym_dependency_annotation_token1] = ACTIONS(1),
    [sym_comment] = ACTIONS(1),
    [sym__newline] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(38),
    [sym_section] = STATE(13),
    [sym_section_header] = STATE(2),
    [aux_sym_source_file_repeat1] = STATE(13),
    [ts_builtin_sym_end] = ACTIONS(3),
    [anon_sym_LBRACK] = ACTIONS(5),
    [sym_comment] = ACTIONS(7),
    [sym__blank_line] = ACTIONS(7),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 6,
    ACTIONS(11), 1,
      sym_option_name,
    ACTIONS(13), 1,
      aux_sym_dependency_annotation_token1,
    ACTIONS(15), 1,
      sym_comment,
    ACTIONS(18), 1,
      sym__blank_line,
    ACTIONS(9), 2,
      ts_builtin_sym_end,
      anon_sym_LBRACK,
    STATE(3), 3,
      sym_option,
      sym_dependency_annotation,
      aux_sym_section_repeat1,
  [22] = 6,
    ACTIONS(11), 1,
      sym_option_name,
    ACTIONS(13), 1,
      aux_sym_dependency_annotation_token1,
    ACTIONS(23), 1,
      sym_comment,
    ACTIONS(26), 1,
      sym__blank_line,
    ACTIONS(21), 2,
      ts_builtin_sym_end,
      anon_sym_LBRACK,
    STATE(5), 3,
      sym_option,
      sym_dependency_annotation,
      aux_sym_section_repeat1,
  [44] = 6,
    ACTIONS(31), 1,
      sym_option_name,
    ACTIONS(33), 1,
      aux_sym_continuation_token1,
    ACTIONS(35), 1,
      sym_comment,
    ACTIONS(38), 1,
      sym__blank_line,
    STATE(7), 2,
      sym_continuation,
      aux_sym_option_repeat1,
    ACTIONS(29), 3,
      ts_builtin_sym_end,
      anon_sym_LBRACK,
      aux_sym_dependency_annotation_token1,
  [66] = 6,
    ACTIONS(43), 1,
      sym_option_name,
    ACTIONS(46), 1,
      aux_sym_dependency_annotation_token1,
    ACTIONS(49), 1,
      sym_comment,
    ACTIONS(52), 1,
      sym__blank_line,
    ACTIONS(41), 2,
      ts_builtin_sym_end,
      anon_sym_LBRACK,
    STATE(5), 3,
      sym_option,
      sym_dependency_annotation,
      aux_sym_section_repeat1,
  [88] = 6,
    ACTIONS(33), 1,
      aux_sym_continuation_token1,
    ACTIONS(57), 1,
      sym_option_name,
    ACTIONS(59), 1,
      sym_comment,
    ACTIONS(62), 1,
      sym__blank_line,
    STATE(8), 2,
      sym_continuation,
      aux_sym_option_repeat1,
    ACTIONS(55), 3,
      ts_builtin_sym_end,
      anon_sym_LBRACK,
      aux_sym_dependency_annotation_token1,
  [110] = 6,
    ACTIONS(33), 1,
      aux_sym_continuation_token1,
    ACTIONS(67), 1,
      sym_option_name,
    ACTIONS(69), 1,
      sym_comment,
    ACTIONS(72), 1,
      sym__blank_line,
    STATE(10), 2,
      sym_continuation,
      aux_sym_option_repeat1,
    ACTIONS(65), 3,
      ts_builtin_sym_end,
      anon_sym_LBRACK,
      aux_sym_dependency_annotation_token1,
  [132] = 6,
    ACTIONS(33), 1,
      aux_sym_continuation_token1,
    ACTIONS(77), 1,
      sym_option_name,
    ACTIONS(79), 1,
      sym_comment,
    ACTIONS(82), 1,
      sym__blank_line,
    STATE(10), 2,
      sym_continuation,
      aux_sym_option_repeat1,
    ACTIONS(75), 3,
      ts_builtin_sym_end,
      anon_sym_LBRACK,
      aux_sym_dependency_annotation_token1,
  [154] = 6,
    ACTIONS(33), 1,
      aux_sym_continuation_token1,
    ACTIONS(77), 1,
      sym_option_name,
    ACTIONS(85), 1,
      sym_comment,
    ACTIONS(88), 1,
      sym__blank_line,
    STATE(11), 2,
      sym_continuation,
      aux_sym_option_repeat1,
    ACTIONS(75), 3,
      ts_builtin_sym_end,
      anon_sym_LBRACK,
      aux_sym_dependency_annotation_token1,
  [176] = 6,
    ACTIONS(93), 1,
      sym_option_name,
    ACTIONS(95), 1,
      aux_sym_continuation_token1,
    ACTIONS(98), 1,
      sym_comment,
    ACTIONS(101), 1,
      sym__blank_line,
    STATE(10), 2,
      sym_continuation,
      aux_sym_option_repeat1,
    ACTIONS(91), 3,
      ts_builtin_sym_end,
      anon_sym_LBRACK,
      aux_sym_dependency_annotation_token1,
  [198] = 6,
    ACTIONS(33), 1,
      aux_sym_continuation_token1,
    ACTIONS(106), 1,
      sym_option_name,
    ACTIONS(108), 1,
      sym_comment,
    ACTIONS(111), 1,
      sym__blank_line,
    STATE(10), 2,
      sym_continuation,
      aux_sym_option_repeat1,
    ACTIONS(104), 3,
      ts_builtin_sym_end,
      anon_sym_LBRACK,
      aux_sym_dependency_annotation_token1,
  [220] = 2,
    ACTIONS(116), 2,
      sym_option_name,
      sym_comment,
    ACTIONS(114), 5,
      ts_builtin_sym_end,
      anon_sym_LBRACK,
      aux_sym_dependency_annotation_token1,
      aux_sym_continuation_token1,
      sym__blank_line,
  [232] = 5,
    ACTIONS(5), 1,
      anon_sym_LBRACK,
    ACTIONS(118), 1,
      ts_builtin_sym_end,
    STATE(2), 1,
      sym_section_header,
    ACTIONS(120), 2,
      sym_comment,
      sym__blank_line,
    STATE(15), 2,
      sym_section,
      aux_sym_source_file_repeat1,
  [250] = 5,
    ACTIONS(126), 1,
      sym__newline,
    STATE(17), 1,
      aux_sym_value_repeat1,
    STATE(33), 1,
      sym_value,
    ACTIONS(122), 2,
      aux_sym_value_token1,
      aux_sym_value_token2,
    ACTIONS(124), 2,
      sym_substitution,
      sym_escape,
  [268] = 5,
    ACTIONS(128), 1,
      ts_builtin_sym_end,
    ACTIONS(130), 1,
      anon_sym_LBRACK,
    STATE(2), 1,
      sym_section_header,
    ACTIONS(133), 2,
      sym_comment,
      sym__blank_line,
    STATE(15), 2,
      sym_section,
      aux_sym_source_file_repeat1,
  [286] = 2,
    ACTIONS(138), 2,
      sym_option_name,
      sym_comment,
    ACTIONS(136), 4,
      ts_builtin_sym_end,
      anon_sym_LBRACK,
      aux_sym_dependency_annotation_token1,
      sym__blank_line,
  [297] = 4,
    ACTIONS(144), 1,
      sym__newline,
    STATE(18), 1,
      aux_sym_value_repeat1,
    ACTIONS(140), 2,
      aux_sym_value_token1,
      aux_sym_value_token2,
    ACTIONS(142), 2,
      sym_substitution,
      sym_escape,
  [312] = 4,
    ACTIONS(152), 1,
      sym__newline,
    STATE(18), 1,
      aux_sym_value_repeat1,
    ACTIONS(146), 2,
      aux_sym_value_token1,
      aux_sym_value_token2,
    ACTIONS(149), 2,
      sym_substitution,
      sym_escape,
  [327] = 2,
    ACTIONS(156), 2,
      sym_option_name,
      sym_comment,
    ACTIONS(154), 4,
      ts_builtin_sym_end,
      anon_sym_LBRACK,
      aux_sym_dependency_annotation_token1,
      sym__blank_line,
  [338] = 2,
    ACTIONS(160), 2,
      sym_option_name,
      sym_comment,
    ACTIONS(158), 4,
      ts_builtin_sym_end,
      anon_sym_LBRACK,
      aux_sym_dependency_annotation_token1,
      sym__blank_line,
  [349] = 2,
    ACTIONS(164), 2,
      sym_option_name,
      sym_comment,
    ACTIONS(162), 4,
      ts_builtin_sym_end,
      anon_sym_LBRACK,
      aux_sym_dependency_annotation_token1,
      sym__blank_line,
  [360] = 4,
    ACTIONS(166), 1,
      aux_sym_section_header_token1,
    ACTIONS(168), 1,
      sym_comment,
    ACTIONS(170), 1,
      sym__newline,
    STATE(30), 1,
      sym__trailing_comment,
  [373] = 4,
    ACTIONS(166), 1,
      aux_sym_section_header_token1,
    ACTIONS(172), 1,
      sym_comment,
    ACTIONS(174), 1,
      sym__newline,
    STATE(37), 1,
      sym__trailing_comment,
  [386] = 4,
    ACTIONS(166), 1,
      aux_sym_section_header_token1,
    ACTIONS(176), 1,
      sym_comment,
    ACTIONS(178), 1,
      sym__newline,
    STATE(40), 1,
      sym__trailing_comment,
  [399] = 2,
    ACTIONS(180), 1,
      aux_sym_section_header_token1,
    ACTIONS(182), 2,
      anon_sym_RBRACK,
      sym_condition,
  [407] = 2,
    ACTIONS(184), 1,
      aux_sym_section_header_token1,
    ACTIONS(186), 2,
      anon_sym_RBRACK,
      sym_condition,
  [415] = 2,
    ACTIONS(188), 1,
      aux_sym_section_header_token1,
    ACTIONS(190), 1,
      sym_section_name,
  [422] = 1,
    ACTIONS(192), 2,
      anon_sym_RBRACK,
      sym_condition,
  [427] = 1,
    ACTIONS(186), 2,
      anon_sym_RBRACK,
      sym_condition,
  [432] = 1,
    ACTIONS(174), 1,
      sym__newline,
  [436] = 1,
    ACTIONS(194), 1,
      sym_section_name,
  [440] = 1,
    ACTIONS(196), 1,
      sym_comment,
  [444] = 1,
    ACTIONS(198), 1,
      sym__newline,
  [448] = 1,
    ACTIONS(200), 1,
      sym__newline,
  [452] = 1,
    ACTIONS(202), 1,
      sym_assignment,
  [456] = 1,
    ACTIONS(204), 1,
      sym__newline,
  [460] = 1,
    ACTIONS(178), 1,
      sym__newline,
  [464] = 1,
    ACTIONS(206), 1,
      ts_builtin_sym_end,
  [468] = 1,
    ACTIONS(208), 1,
      sym__newline,
  [472] = 1,
    ACTIONS(210), 1,
      sym__newline,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 22,
  [SMALL_STATE(4)] = 44,
  [SMALL_STATE(5)] = 66,
  [SMALL_STATE(6)] = 88,
  [SMALL_STATE(7)] = 110,
  [SMALL_STATE(8)] = 132,
  [SMALL_STATE(9)] = 154,
  [SMALL_STATE(10)] = 176,
  [SMALL_STATE(11)] = 198,
  [SMALL_STATE(12)] = 220,
  [SMALL_STATE(13)] = 232,
  [SMALL_STATE(14)] = 250,
  [SMALL_STATE(15)] = 268,
  [SMALL_STATE(16)] = 286,
  [SMALL_STATE(17)] = 297,
  [SMALL_STATE(18)] = 312,
  [SMALL_STATE(19)] = 327,
  [SMALL_STATE(20)] = 338,
  [SMALL_STATE(21)] = 349,
  [SMALL_STATE(22)] = 360,
  [SMALL_STATE(23)] = 373,
  [SMALL_STATE(24)] = 386,
  [SMALL_STATE(25)] = 399,
  [SMALL_STATE(26)] = 407,
  [SMALL_STATE(27)] = 415,
  [SMALL_STATE(28)] = 422,
  [SMALL_STATE(29)] = 427,
  [SMALL_STATE(30)] = 432,
  [SMALL_STATE(31)] = 436,
  [SMALL_STATE(32)] = 440,
  [SMALL_STATE(33)] = 444,
  [SMALL_STATE(34)] = 448,
  [SMALL_STATE(35)] = 452,
  [SMALL_STATE(36)] = 456,
  [SMALL_STATE(37)] = 460,
  [SMALL_STATE(38)] = 464,
  [SMALL_STATE(39)] = 468,
  [SMALL_STATE(40)] = 472,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [9] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_section, 1, 0, 0),
  [11] = {.entry = {.count = 1, .reusable = false}}, SHIFT(35),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [15] = {.entry = {.count = 2, .reusable = false}}, REDUCE(sym_section, 1, 0, 0), SHIFT(3),
  [18] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_section, 1, 0, 0), SHIFT(3),
  [21] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_section, 2, 0, 0),
  [23] = {.entry = {.count = 2, .reusable = false}}, REDUCE(sym_section, 2, 0, 0), SHIFT(5),
  [26] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_section, 2, 0, 0), SHIFT(5),
  [29] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_dependency_annotation, 2, 0, 0),
  [31] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_dependency_annotation, 2, 0, 0),
  [33] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [35] = {.entry = {.count = 2, .reusable = false}}, REDUCE(sym_dependency_annotation, 2, 0, 0), SHIFT(7),
  [38] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_dependency_annotation, 2, 0, 0), SHIFT(7),
  [41] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_section_repeat1, 2, 0, 0),
  [43] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_section_repeat1, 2, 0, 0), SHIFT_REPEAT(35),
  [46] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_section_repeat1, 2, 0, 0), SHIFT_REPEAT(39),
  [49] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_section_repeat1, 2, 0, 0), SHIFT_REPEAT(5),
  [52] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_section_repeat1, 2, 0, 0), SHIFT_REPEAT(5),
  [55] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_option, 3, 0, 0),
  [57] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_option, 3, 0, 0),
  [59] = {.entry = {.count = 2, .reusable = false}}, REDUCE(sym_option, 3, 0, 0), SHIFT(8),
  [62] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_option, 3, 0, 0), SHIFT(8),
  [65] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_dependency_annotation, 3, 0, 0),
  [67] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_dependency_annotation, 3, 0, 0),
  [69] = {.entry = {.count = 2, .reusable = false}}, REDUCE(sym_dependency_annotation, 3, 0, 0), SHIFT(10),
  [72] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_dependency_annotation, 3, 0, 0), SHIFT(10),
  [75] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_option, 4, 0, 0),
  [77] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_option, 4, 0, 0),
  [79] = {.entry = {.count = 2, .reusable = false}}, REDUCE(sym_option, 4, 0, 0), SHIFT(10),
  [82] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_option, 4, 0, 0), SHIFT(10),
  [85] = {.entry = {.count = 2, .reusable = false}}, REDUCE(sym_option, 4, 0, 0), SHIFT(11),
  [88] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_option, 4, 0, 0), SHIFT(11),
  [91] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_option_repeat1, 2, 0, 0),
  [93] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_option_repeat1, 2, 0, 0),
  [95] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_option_repeat1, 2, 0, 0), SHIFT_REPEAT(34),
  [98] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_option_repeat1, 2, 0, 0), SHIFT_REPEAT(10),
  [101] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_option_repeat1, 2, 0, 0), SHIFT_REPEAT(10),
  [104] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_option, 5, 0, 0),
  [106] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_option, 5, 0, 0),
  [108] = {.entry = {.count = 2, .reusable = false}}, REDUCE(sym_option, 5, 0, 0), SHIFT(10),
  [111] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_option, 5, 0, 0), SHIFT(10),
  [114] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_continuation, 2, 0, 0),
  [116] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_continuation, 2, 0, 0),
  [118] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [120] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [122] = {.entry = {.count = 1, .reusable = false}}, SHIFT(17),
  [124] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [126] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [128] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [130] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(27),
  [133] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(15),
  [136] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_section_header, 4, 0, 0),
  [138] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_section_header, 4, 0, 0),
  [140] = {.entry = {.count = 1, .reusable = false}}, SHIFT(18),
  [142] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [144] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_value, 1, 0, 0),
  [146] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_value_repeat1, 2, 0, 0), SHIFT_REPEAT(18),
  [149] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_value_repeat1, 2, 0, 0), SHIFT_REPEAT(18),
  [152] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_value_repeat1, 2, 0, 0),
  [154] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_section_header, 6, 0, 0),
  [156] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_section_header, 6, 0, 0),
  [158] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_section_header, 5, 0, 0),
  [160] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_section_header, 5, 0, 0),
  [162] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_section_header, 7, 0, 0),
  [164] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_section_header, 7, 0, 0),
  [166] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [168] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [170] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [172] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [174] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [176] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [178] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [180] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [182] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [184] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [186] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [188] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [190] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [192] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [194] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [196] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [198] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [200] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [202] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [204] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__trailing_comment, 2, 0, 0),
  [206] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [208] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [210] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_buildout(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
