include Makefile

test_without_coverage:
	PYTHONWARNINGS=$(PYTHONWARNINGS) BUILDOUT_PIP_NO_BUILD_ISOLATION=1 bin/test -c -vvv

test_with_coverage:
	PYTHONWARNINGS=$(PYTHONWARNINGS) BUILDOUT_PIP_NO_BUILD_ISOLATION=1 RUN_COVERAGE= COVERAGE_REPORT= /home/buildout/sandbox/bin/test -c -vvv
