.. zc.buildout documentation master file, created by
   sphinx-quickstart on Sun Feb 20 10:46:26 2011.
   You can adapt this file completely to your liking, but it should at least
   contain the root `toctree` directive.

Welcome to zc.buildout's documentation!
=======================================

Contents:

.. toctree::
   :maxdepth: 4

   index
   how-tos

Indices and tables
==================

* :ref:`genindex`
* :ref:`modindex`
* :ref:`search`

