name: Debian containers

on:
  push:
  pull_request:
  # Allow to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name != github.event.pull_request.base.repo.full_name
    strategy:
      fail-fast: false
      matrix:
        python-version: ["2.7", "3.5", "3.6", "3.7", "3.8", "3.9", "3.10", "3.11"]

    steps:
    - uses: actions/checkout@v3
    - name: Test in container with Python ${{ matrix.python-version }}
      env:
        PYTHON_VER: ${{matrix.python-version}}
        BUILD_TYPE: debian_containers
      run: |
        ./ci_build.sh
